<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="181" started-at="2016-08-10T19:30:20Z" finished-at="2016-08-10T19:30:20Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="181" started-at="2016-08-10T19:30:20Z" finished-at="2016-08-10T19:30:20Z">
      <class name="com.ts.tests.HomePageTest">
        <test-method status="PASS" signature="beforeSuite()[pri:0, instance:com.ts.tests.HomePageTest@64616ca2]" name="beforeSuite" is-config="true" duration-ms="32451" started-at="2016-08-10T12:29:47Z" finished-at="2016-08-10T12:30:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:com.ts.tests.HomePageTest@64616ca2]" name="beforeClass" is-config="true" duration-ms="7" started-at="2016-08-10T12:30:20Z" finished-at="2016-08-10T12:30:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="FAIL" signature="testClickSignupNow()[pri:0, instance:com.ts.tests.HomePageTest@64616ca2]" name="testClickSignupNow" duration-ms="70" started-at="2016-08-10T12:30:20Z" finished-at="2016-08-10T12:30:20Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.ts.pages.HomePage.clickSignupNow(HomePage.java:27)
	at com.ts.tests.HomePageTest.testClickSignupNow(HomePageTest.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testClickSignupNow -->
        <test-method status="PASS" signature="afterSuite()[pri:0, instance:com.ts.tests.HomePageTest@64616ca2]" name="afterSuite" is-config="true" duration-ms="5339" started-at="2016-08-10T12:30:20Z" finished-at="2016-08-10T12:30:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- com.ts.tests.HomePageTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
